export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SET_GLOBAL_SETUP_STATE = "SET_GLOBAL_SETUP_STATE";
export const SET_GLOBAL_NETWORTH_STATE = "SET_GLOBAL_NETWORTH_STATE";

export const SET_CURRENCY = "SET_CURRENCY";

export const SET_USER_CONTENT = "SET_USER_CONTENT";
export const SET_USER_CONTENT_FAIL = "SET_USER_CONTENT_FAIL";
export const SET_USER_WALLET = "SET_USER_WALLET";
export const CLEAR_USER = "CLEAR_USER";

export const ADD_USER_EXPENSE = "ADD_USER_EXPENSE";
export const MODIFY_USER_EXPENSE = "MODIFY_USER_EXPENSE";
export const ADD_USER_INCOME = "ADD_USER_INCOME";
export const MODIFY_USER_INCOME = "MODIFY_USER_INCOME";
export const ADD_USER_ASSET = "ADD_USER_ASSET";
export const MODIFY_USER_ASSET = "MODIFY_USER_ASSET";
