name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd github/personal-finance-manager
            git pull origin main

            cd be/java-sb
            pkill -f "java -jar target/java-sb-0.0.1-SNAPSHOT.jar"

            mvn clean package
            nohup java -jar target/java-sb-0.0.1-SNAPSHOT.jar > console.log 2>&1 &
